development:
  adapter: postgresql
  encoding: unicode
  database: watchio_development
  pool: 5

test:
  adapter: postgresql
  encoding: unicode
  database: watchio_test
  pool: 5

production:
  adapter: postgresql
  encoding: unicode
  database: watchio_production
  pool: 5
